/*
  File: SYMBOLS.H
  Copyright (C) Psion PLC 1993
  Started by : DavidW
*/

/* Names of the pictures in the symbols font */

#define WS_SYMBOL_SHOW_CR         0

#define WS_SYMBOL_ELLIPSIS        1
/* #define WS_WIDTH_ELLIPSIS         6  */

#define WS_SYMBOL_PSION           2

#define WS_SYMBOL_POWERX          3

#define WS_SYMBOL_DIAMOND         4
#define WS_SYMBOL_NOTE_ICON       4

#define WS_SYMBOL_PHONE           5

#define WS_SYMBOL_PADLOCK         6 

#define WS_SYMBOL_HARD_HYPHEN     7

#define WS_SYMBOL_SHOW_SPACE      8

#define WS_SYMBOL_SHOW_TAB        9

#define WS_SYMBOL_LINE_BREAK      10

#define WS_SYMBOL_SHIFTED         11
#define WS_SYMBOL_SQROOT          11

#define WS_SYMBOL_TICK            12

#define WS_SYMBOL_DOWN_ARROWHEAD  13

#define WS_SYMBOL_SOFT_HYPHEN     14

#define WS_SYMBOL_HARD_SPACE      15

#define WS_SYMBOL_RIGHT_ARROWHEAD 16

#define WS_SYMBOL_LEFT_ARROWHEAD  17

#define WS_SYMBOL_WHITE_BOX       18

#define WS_SYMBOL_PASS_UNDERLINE  19 

#define WS_SYMBOL_GREY_BOX        20

#define WS_SYMBOL_BLACK_BOX       22

#define WS_SYMBOL_UP_KEY          24

#define WS_SYMBOL_DOWN_KEY        25

#define WS_SYMBOL_RIGHT_KEY       26

#define WS_SYMBOL_LEFT_KEY        27

#define WS_SYMBOL_MARGIN_CURSOR   28

#define WS_SYMBOL_BELL            29

#define WS_SYMBOL_UP_ARROWHEAD    30

#define WS_SYMBOL_NS          31

#define WS_SYMBOL_POWER2          253

#define WS_SYMBOL_BULLET          254

/* Positioning of special characters in the special array */

#define H_SC_TPLUS      0       /* T is for Tag */
#define H_SC_TMINUS     1
#define H_SC_TSTAR      2
#define H_SC_TSLASH     3

#define H_SC_ILESS      4       /* I is for Incrementer */
#define H_SC_ICOMMA     5
#define H_SC_IMORE      6
#define H_SC_IDOT       7

#define H_SC_HFANCY     8       /* H is for Hyphen */

#define H_SC_LLN        9       /* LL is for LatLong editor */
#define H_SC_LLS        10
#define H_SC_LLW        11
#define H_SC_LLE        12
